name: Release
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.0.0
      - name: Initialize git user
        run: |
            git config --global user.name "Release It!"
            git config --global user.email "release-it@example.com"
      - name: Install release-it and plugins 
        run: npm i -g release-it @csmith/release-it-calver-plugin 
      - name: List installed packages
        run: npm -g list
      - name: Run release-it
        run: release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
